### PR TITLE
upgrade go to go1.11

### LINKED ISSUE #116: update golang version
Could we have the go version included in the go and full docker images updated?

The lack of go module support with go >= 1.11 makes it very difficult to work on projects that use go modules, or other go code outside of the gopath.

Thanks.

### PR DESCRIPTION
**Pull request by lanrat**
fixes #116

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@lanrat Thanks for the PR. Can you please sign the commit? e.g. "git commit --amend -s"

The CI unfortunately does not work well for non-committers, as you can see. As a work-around I created a mirror PR in my fork, so we can have CI results. Here it is: https://github.com/marcdumais-work/theia-apps/pull/6

P.S. It's expected that the full images will fail CI at this time...

**Comment by lanrat** [comment]
@marcdumais-work the commit should now be signed.

**Comment by marcdumais-work** [comment]
> @marcdumais-work the commit should now be signed.

I think something went wrong: I now see 3 commits :(

**Comment by lanrat** [comment]
@marcdumais-work that thought crossed my mind as well.

I assume that you mean my changes to `GOPATH`, I did not change `GOROOT`. If I am mistaken please correct me.

When go introduced modules in go 1.11, it changed how go code should be structured. Go code that is build using modules should not reside in to `GOPATH`, which is where the current theia containers store their work. Go is working to eventually deprecate the need for a `GOPATH` variable entirely. So it sounds like we should update the README as well to reflect this change?

What are your thoughts?

**Comment by marcdumais-work** [comment]
Hi @lanrat, apologies for the slow responses. 
> you mean my changes to GOPATH, I did not change GOROOT

I think I was wrong - this should work. I'll give it a try. 

 > So it sounds like we should update the README as well to reflect this change?

+1. (Ouch, the README is badly outdated in general). I am not a golang developer, so please set it up as you think is best and document how one would best use it. I'll be the beta-tester of these instructions, to validate the PR. Thanks!

**Comment by lanrat** [comment]
I just took another look at this. In addition to the README being outdated there doesn't seem to be any documentation for the language specific images.

**Comment by vince-fugnitto** [comment]
Closing the issue as the `theia-full-docker` image currently has a `go` version of: 

https://github.com/theia-ide/theia-apps/blob/4abc544aa97d4a2c34e7a0e7ccf3444ffd01bc9f/theia-full-docker/Dockerfile#L83

Verified on 4abc544

Thank you for contributing! :+1:

**Pull request closed without merging**
