### PR TITLE
Python3 image

### LINKED ISSUE #74: Support of Python3
It's great to see the Docker for Python added. I've tried it and it works well. However, it is for Python2 only currently. Can we add support of Python3?

### PR DESCRIPTION
**Pull request by sr229**
Resolves #74 

Adds a Python 3-specific image.

### CODE REVIEW

**Comment by sr229** [comment]
Could've used and copy out the Python3 image in DockerHub but it seems they compile it from source, may cause unecessary image sizing problems.

**Comment by jgbradley1** [comment]
Should update the base image to Node 10 now.

**Comment by jgbradley1** [comment]
Auto-completion and suggestions are not working for me when I try this image. I get the following error message when running the docker image and create a test python file.

```
root ERROR Python: /usr/bin/python: No module named pyls
```

It install expects python-language-server to be installed for Python 2.7. One workaround I tried was to put `alias python=python3` in the Dockerfile but it does not work as expected. Also using alias is the wrong way to do it according to the discussions [here](https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3).

**Comment by marcdumais-work** [comment]
Hi @sr229 , @jgbradley1,

Thanks for your continued work and validation of this PR. 

I wanted to bring to your attention a new opportunity: Theia is increasingly able to re-use VS Code extensions as-is. I do not know if anyone has tried the [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) one yet, but it's likely to work well, and if not we can work in the main Theia repo to add any missing VS Code APIs. 

As an example, here's the corresponding PR for [golang](https://github.com/theia-ide/theia-apps/pull/146), where we replaced the Theia extension by the VS Code one.

**Comment by jgbradley1** [comment]
@marcdumais-work @sr229 

I worked up a quick example with the [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension and removed `@theia/python`. It works quite well out of the box. I see no immediate error messages on startup. A few issues exist with debugging and importing/running jupyter notebooks.

**Comment by marcdumais-work** [comment]
> @marcdumais-work @sr229
> 
> I worked up an [example](https://github.com/jgbradley1/theia-python3) with the [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension and removed `@theia/python`. It works quite well out of the box. I see no immediate error messages on startup. A few issues exist with debugging and importing/running jupyter notebooks.

Nice! About debugging: I am not sure about Python, but often debuggers use `ptrace` and so require the container to be run with special permssions. Not sure if you may have tried something like e.g. [here](https://github.com/theia-ide/theia-apps/blob/master/theia-go-docker/README.md): 
 `docker run --security-opt seccomp=unconfined ...`?

**Pull request closed without merging**
