### PR TITLE
docker full: fixed gpg typo (ubuntu 18.04)

### PR DESCRIPTION
**Pull request by avelino**
It is some kind of IPV6-related issue to ipv4 instead.

refs:
- https://github.com/theia-ide/theia-apps/pull/136#discussion_r261685806
- https://github.com/jacobalberty/unifi-docker/issues/64#issuecomment-454961479

thanks @marcdumais-work

### CODE REVIEW

**Comment by marcdumais-work** [comment]
Hi @avelino 

Looking good so far. 

There is a second block, just a bit lower, that has the same issue: 
https://github.com/theia-ide/theia-apps/pull/140/files#diff-248e1209aca6bd97b133a2985a672563L59

**Comment by marcdumais-work** [comment]
Thanks @avelino - it seems to work better now, at least on my laptop. 

Could you please squash these two commits together and sign (`git commit -s`) the resulting commit?

**Comment by avelino** [comment]
@marcdumais-work done
You could do squash on merge the GitHub interface
https://help.github.com/en/articles/merging-a-pull-request#merging-a-pull-request-on-github

**Comment by marcdumais-work** [comment]
@avelino 
Thanks for squashing the commits.

> You could do squash on merge the GitHub interface

We tend to prefer the "rebase and merge" way, but have not been 100% consistent.

**Comment by marcdumais-work** [comment]
@avelino I think the commit message could better describe the change. Can you update it? I suggest something like "[full] Optimized fetching GPG keys for node/yarn installs".

And please also sign the commit: 
```git commit --amend -s```

Thanks!

**Comment by avelino** [comment]
@marcdumais-work done

**Comment by marcdumais-work** [comment]
@avelino Thanks for signing the commit. However I still see the original commit message: 

image

Can you update that?

**Comment by avelino** [comment]
I (Avelino) do not see problem in having to change both my contribution. It is important to have this action lead contributors away from the project.

Sorry for telling the truth

**Comment by marcdumais-work** [comment]
@avelino I think it's important to have a commit message that correctly reflects what was changed. Thanks for making the update.

**Pull request merged**
