### PR TITLE
Openshift Docker Image

### PR DESCRIPTION
**Pull request by JamesDrummond**
Openshift requires that user not have root user permissions. Openshift defaults to a random user id number that does not have root permissions https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines . This means that passwd file needs to be updated to include random user in startup script to ensure applications run correctly. Permissions of certain folders need be changed to be readable and executed by this random user that belongs to the group "root" by default.

Theia team would need to add an Docker image to the automated builds for docker hub which builds after base image 'theiaide/theia' is built. Name needs to pick for this image but could be 'theiaide/theia-openshift'.

Related issue https://github.com/theia-ide/theia/issues/1655

Signed-off-by: James Drummond \<james.m.drummond@gmail.com\>

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by JamesDrummond** [comment]
I wrote an article on how to use it which I could convert to markdown that can be add to docs if requested. I use a lot of photos so not sure if this repo would be a good place for it. https://medium.com/@james_devcomb/theia-on-openshift-f4ee8832a587

**Comment by marcdumais-work** [comment]
@JamesDrummond Do you know if the free OpenShift "starter" account is able to run the Theia image? It has 1GB memory and storage, so if must be tight, if enough.

**Comment by marcdumais-work** [comment]
>Theia team would need to add an Docker image to the automated builds for docker hub which builds after base image 'theiaide/theia' is built.

Could we just add the new image in ```.travis.yml```, so it's built and pushed to docker hub by Travis? 

https://github.com/theia-ide/theia-apps/blob/9865ec23ad00f07302241903dd3b0485a5cc73c4/.travis.yml#L19-L27

**Comment by JamesDrummond** [comment]
@marcdumais-work If you are asking me I don't know about travis CI.

Works great on openshift.io .

image

**Comment by marcdumais-work** [comment]
@JamesDrummond ok, I can add it in a separate PR, after we merge this one here.

**Comment by marcdumais-work** [comment]
I have just tried your pre-built image, in OpenShift. Nice article/guide, @JamesDrummond . It indeed works quite well. I noticed a few problems, but they are also present in the base image.

**Comment by marcdumais-work** [comment]
Merged - thanks @JamesDrummond

**Comment by marcdumais-work** [comment]
@JamesDrummond Could you please "move" the issue to this repo here? You could just open a new one and copy the content from https://github.com/theia-ide/theia/issues/1747 to it.

**Comment by JamesDrummond** [comment]
@marcdumais-work Done. https://github.com/theia-ide/theia-apps/issues/43

**Pull request merged**
