### PR TITLE
ruby: remove ruby docker image

### PR DESCRIPTION
**Pull request by vince-fugnitto**
**Description**

The following pull-request removes the `theia-ruby-docker` image for the following reasons:
- the image is outdated and unmaintained
  - the image currently uses `node 8` and does not build.
  - the image is not part of CI for some time.
- the `theia-full` image contains the necessary ruby environment and [vscode-ruby](https://open-vsx.org/extension/rebornix/ruby) extension.

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Review by marcdumais-work — APPROVED** [review]
LGTM, thanks @vince-fugnitto

**Comment by marcdumais-work** [comment]
cc: @jbicker FYI

**Comment by vince-fugnitto** [comment]
@jbicker do you have objections to removing the image?

**Comment by jbicker** [comment]
> @jbicker do you have objections to removing the image?

Thanks for asking! No objections at all. :-)

**Pull request merged**
