### PR TITLE
Update CMake for theia-cpp images

### PR DESCRIPTION
**Pull request by Mizux**
Bump CMake from 3.10.2 to 3.17.0 (the latest stable) using the kitware installer.

### CODE REVIEW

**Comment by marcdumais-work** [comment]
Hi @Mizux ,

Thanks for this contribution. 

Would you be interested to add CMake to the `theia-full` image as well in this PR? I notice it doesn't have it at the moment, and CMake can be very useful for C/C++ since it has the ability to generate the compilation database that our language server (`clangd`) needs for precise operation. I would add it around here:
https://github.com/theia-ide/theia-apps/blob/master/theia-full-docker/Dockerfile#L125

**Comment by marcdumais-work** [comment]
@Mizux Not directly related to this PR: I noticed according to your GH profile that you seem to have a keen interest in CMake and C++. One related thing we're missing at the moment in this image is an example workspace, that contains a sample C/C++ project that can easily be built, and its `Compilation Database` generated. A CMake project seems like it would be ideal. Some type of "HelloWorld" program would work. 

This could then be used for tests, automated and manual, and for users who want to see how to setup such a project and/or try the Theia app with it. Let me know if you'd be interested to contribute such a thing :)

**Comment by Mizux** [comment]
> @Mizux Not directly related to this PR: I noticed according to your GH profile that you seem to have a keen interest in CMake and C++. One related thing we're missing at the moment in this image is an example workspace, that contains a sample C/C++ project that can easily be built, and its `Compilation Database` generated. A CMake project seems like it would be ideal. Some type of "HelloWorld" program would work.
> 
> This could then be used for tests, automated and manual, and for users who want to see how to setup such a project and/or try the Theia app with it. Let me know if you'd be interested to contribute such a thing :)

Do you mean extending: https://github.com/eclipse-theia/theia-cpp-extensions/tree/master/examples/cpp-debug-workspace ?

To be honest I'm mostly using terminal/gvim (+YouCompleteMe) and sometime QtCreator (for refactoring since YCM is not so good) for CMake/C++.
On wednesday I start to give a try to vscode then yesterday I just found theia and gitpod (which already provide cmake 3.17) project and start to dig how I could work with it since web development and tools (i.e. ide) seems to be the way to go for a mostly embedded c/c++ dev dinosaure like me ;)

**Comment by Mizux** [comment]
@marcdumais-work can you restart the travis jobs ? it seems there is an issue in go fetch during full image build (which is before my patch)

**Comment by marcdumais-work** [comment]
> Do you mean extending: https://github.com/eclipse-theia/theia-cpp-extensions/tree/master/examples/cpp-debug-workspace ?

Yes, something like that but with a CMake "setup" to build the project rather than a raw "gcc" command. Note: because of license differences we can't copy-over that workspace here. 

> On wednesday I start to give a try to vscode then yesterday I just found theia and gitpod (which already provide cmake 3.17) project and start to dig how I could work with it since web development and tools (i.e. ide) seems to be the way to go for a mostly embedded c/c++ dev dinosaure like me ;)

Welcome to the Theia world :) You may not be aware, but Google Cloud Shell is based on Theia (we have a committer from Google in the main project). 

I understand if this request may fall outside of your area of interest, I just thought I would mention it in case you'd be interested.

Happy hacking :)

**Comment by marcdumais-work** [comment]
> @marcdumais-work can you restart the travis jobs ? it seems there is an issue in go fetch during full image build (which is before my patch)

There are a few common patters of errors on the CI in this repo, but what I see now is unusual. Please ignore it for now - I doubt it's related to your change. I'll build `theia-full` from this PR locally to confirm.

**Pull request merged**
