### PR TITLE
docs: add windows command

### PR DESCRIPTION
**Pull request by Jeff-Tian**

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@Jeff-Tian do you mind [signing-off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) your commit? 
It is the reason for the failed CI check (DCO)

**Comment by vince-fugnitto** [comment]
@Jeff-Tian were you able to successfully run the images on Windows?
I assume if you ran the images through [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) (Windows Subsystem Linux) it worked fine.

**Comment by Jeff-Tian** [comment]
@vince-fugnitto I successfully ran the images by using the `%cd%` command  on plain Windows.
I will check it on WSL next time.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I successfully ran the images by using the `%cd%` command on plain Windows.
> I will check it on WSL next time.

I was just surprised it worked so well on Windows when the base image is Linux.
Which image(s) have you tested on Windows?

**Comment by Jeff-Tian** [comment]
> @Jeff-Tian were you able to successfully run the images on Windows?
> I assume if you ran the images through [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) (Windows Subsystem Linux) it worked fine.

Sadly it doesn't work out of the box on WSL. It seems the mounted folder is empty, so the IDE shows no files.

image

image

**Comment by Jeff-Tian** [comment]
> > @vince-fugnitto I successfully ran the images by using the `%cd%` command on plain Windows.
> > I will check it on WSL next time.
> 
> I was just surprised it worked so well on Windows when the base image is Linux.
> Which image(s) have you tested on Windows?

What did you mean by `which image(s) have I tested`? I ran the image `theiaide/theia:next`.

Does `docker info` gives you meaningful messages?

```
C:\Users\Jeff\alpha>docker info
Client:
 Debug Mode: false

Server:
 Containers: 23
  Running: 1
  Paused: 0
  Stopped: 22
 Images: 51
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: TLTU:NP5T:E7VA:LUYA:YUCM:FHOK:2P2B:JGXM:IPUB:LXPN:ECE6:PYK3
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 30
  Goroutines: 45
  System Time: 2019-09-29T18:39:29.8571401Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by Jeff-Tian** [comment]
image

**Comment by marcdumais-work** [comment]
@Jeff-Tian Thanks for the details. It's really nice that such Linux-based images can work on Windows as well (though a bit surprising to me).

**Pull request merged**
