### PR TITLE
Fix for #253 - Rust Channel update

### PR DESCRIPTION
**Pull request by dwjbosman**
Fix for #253 

Channel date has been updated.

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@marcdumais-work the CI is still failing at the same point, are we sure that it is the proper fix?

https://travis-ci.org/theia-ide/theia-apps/jobs/602497745#L1707-L1723

**Comment by dwjbosman** [comment]
> @marcdumais-work the CI is still failing at the same point, are we sure that it is the proper fix?
> 
> https://travis-ci.org/theia-ide/theia-apps/jobs/602497745#L1707-L1723

Oh, I see.

I updated the channel argument in the Makefile, but not the default value in the Dockerfile (which is used by travis).

I'll update that as well

**Comment by vince-fugnitto** [comment]
Unfortunately the CI is still failing for `theia-rust-docker:next` :(

https://travis-ci.org/theia-ide/theia-apps/jobs/603027093#L1535-L1543

**Comment by dwjbosman** [comment]
Now Travis log contains  an "operation not permitted".

However if I build the image locally it succeeds.

The build_container.sh calls docker build. I ran this locally:

In theia-rust-docker:

`docker build --build-arg "version=next" --build-arg "NODE_VERSION=10.15.3"  -t theia-rust-docker `

Can anyone else try this

**Comment by marcdumais-work** [comment]
> Can anyone else try this?

Trying now

**Comment by marcdumais-work** [comment]
> Trying now

It built locally for me as well, using the same `docker build` command as above.

**Comment by marcdumais-work** [comment]
@dwjbosman I tried a few things to troubleshoot the issue and I am left clueless at to why we have this result. 

Searching around for the error, it seems likely this is permission-related, but I do not understand why this happens on Travis but not locally. Maybe some Docker weirdness is at play.

**Comment by dwjbosman** [comment]
I will do some online research later

**Comment by vince-fugnitto** [comment]
I've updated the PR to include the following update to the Travis config file.
I've added the config property for `sudo: required` which fixes issues regarding operations which are not permitted. The same property is present in the main repository. Hopefully it will fix the issue.

I've also taken the liberty of squashing the PR so that the `DCO` check successfully passes.

**Comment by vince-fugnitto** [comment]
Unfortunately it doesn't look like adding `sudo: required` works correctly.
I've seen some issues regarding the use of `cargo` and `rustup` and how permissions must be updated.

**Comment by vince-fugnitto** [comment]
@dwjbosman have you gotten a chance to re-try to see how to resolve the error, the image is still failing CI.

**Comment by vince-fugnitto** [comment]
@dwjbosman great ! the CI is now passing again :)
The only thing to do would be to clean up the history so it can be merged.

**Comment by dwjbosman** [comment]
Another issue is that even though I pin the rust version to a specific channel (nightly-<date>) after some time the image will not build anymore. It seems as if some Rust components are not tied to the specific channel. 

    On Friday, November 29, 2019, 12:54:06 AM GMT+1, Vincent Fugnitto <notifications@github.com> wrote:  
 
 
@dwjbosman great ! the CI is now passing again :)
The only thing to do would be to clean up the history so it can be merged.

**Comment by marcdumais-work** [comment]
> Another issue is that even though I pin the rust version to a specific channel (nightly-<date>) after some time the image will not build anymore. It seems as if some Rust components are not tied to the specific channel. 

Hi @dwjbosman ,

One potential approach would be to split this image in two: have a base image that has the Rust tools and as-little-else-as-possible (minimising the need to rebuild it for reasons other than updating the Rust tools), and then have a second image that extends the latest version of the first one to add the Theia application and everything else that's needed. This way we would have control when to update the Rust tools and rebuild/publish a new version of the first image.  Between updates, we would keep re-using the existing version of the first image that's known to work well.

Thinking of it, it could be even simpler: have our CI re-build the first image nightly, using e.g. the most recent version of Rust tools (nightly channel or such?), and whenever it builds, publish it as e.g. `theiaide/theia-rust-image-base:latest`. The second image can start from that (`FROM theiaide/theia-rust-image-base:latest`), which will automatically pick-up the last one that built. This would require tweaks in how we do CI / test the images, unless you setup the first image to be built / published elsewhere and we just consume it from this repo here. (there is precedent for doing this type of thing: https://github.com/theia-ide/theia-apps/blob/master/theia-swift-docker/Dockerfile#L28)

WDTY?

**Comment by marcdumais-work** [comment]
I have just confirmed that this PR still passes CI. Even though the longer-term strategy is not yet determined, should we merge this for right now? 

@dwjbosman if you have the time, could you rebase this PR and squash the commits? Else maybe @vince-fugnitto can take care of this, preserving your authorship of the resulting commit.

**Comment by vince-fugnitto** [comment]
@marcdumais-work I've rebased it, we can wait for the CI to pass before merging :)

**Comment by vince-fugnitto** [comment]
@marcdumais-work the CI now passes successfully for **rust**, shall we merge?

**Comment by marcdumais-work** [comment]
> @marcdumais-work the CI now passes successfully for **rust**, shall we merge?

Yes, please do.

**Pull request merged**
