### PR TITLE
Pin vscode-json-languageserver to 1.2.2

### LINKED ISSUE #333: Json language services not working
Language services for json files no longer seem to work.

This can be observed with yesterday's build:
```
docker run --rm --init -p 3000:3000 theiaide/theia:1.1.0-next.2c16d4e0
```
then open a json file, for example the preferences, try to complete, but only the "default" completions show up.
In the Output pane from JSON, we can see error message:
```
[Error - 10:30:52] Notification handler 'textDocument/didOpen' failed with message: Invalid TextDocumentSyncKind: [object Object]
```
image

For reference, an old tag where json language services were working: `theiaide/theia:0.16.0-next.77297761`. One difference is the version picked for `vscode-json-languageserver@^1.2.1`, `1.2.2` was OK and nowadays we have `1.2.3` which seems to cause this incompatibility.

At least if I run use this patch for force the resolution to `1.2.2`, language services are working as expected:
```patch
diff --git a/theia-docker/latest.package.json b/theia-docker/latest.package.json
index 57b4ebf..d69129a 100644
--- a/theia-docker/latest.package.json
+++ b/theia-docker/latest.package.json
@@ -37,6 +37,7 @@
     "resolutions": {
         "vscode-languageserver-protocol": "3.15.0-next.9",
         "vscode-languageserver-types": "3.15.0-next.5",
+        "vscode-json-languageserver": "1.2.2",
         "**/vscode-json-languageserver/**/vscode-languageserver": "6.0.0-next.1"
     },
     "theiaPluginsDir": "plugins",
```

If you think this patch is correct and want me to submit a PR updating all `package.json` from this repository to have this resolution, let me know.

### PR DESCRIPTION
**Pull request by perrinjerome**
1.2.3 seems to cause incompatibities.

Fixes #333

Signed-off-by: Jérome Perrin <jerome@nexedi.com>

### CODE REVIEW

**Comment by marcdumais-work** [comment]
Hi @perrinjerome ,

I do not think your PR is the cause for the CI failing. A few are expected to fail right now: both full image and rust. I've restarted the others that had failed. Let's see if a couple more pass now :)

**Comment by marcdumais-work** [comment]
I have tested one app: `theia-docker` and confirmed that with the PR `vscode-json-languageserver@1.2.2` is pulled. However now there seems to be no syntax coloring (for JSON and possibly more):

image

I think the `resolutions` entry may be interfering with each-other. Let me try to remove a few that may no longer be needed and see if that helps:

```
$ yarn why vscode-json-languageserver
yarn why v1.17.3
[1/4] Why do we have the module "vscode-json-languageserver"...?
[2/4] Initialising dependency graph...
warning Resolution field "vscode-languageserver-types@3.15.0-next.5" is incompatible with requested version "vscode-languageserver-types@^3.15.1"
warning Resolution field "vscode-languageserver-protocol@3.15.0-next.9" is incompatible with requested version "vscode-languageserver-protocol@^3.15.3"
warning Resolution field "vscode-languageserver-types@3.15.0-next.5" is incompatible with requested version "vscode-languageserver-types@^3.15.1"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "vscode-json-languageserver@1.2.2"
info Reasons this module exists
   - "@theia#json" depends on it
   - Hoisted from "@theia#json#vscode-json-languageserver"
info Disk size without dependencies: "76KB"
info Disk size with unique dependencies: "6.8MB"
info Disk size with transitive dependencies: "14.69MB"
info Number of shared dependencies: 14
Done in 0.69s.
```

**Comment by marcdumais-work** [comment]
> update: I think this was due to a manipulation mistake on my part - please ignore for now

Confirmed - now it works as expected, with the JSON LS providing completions. :+1: 

I think these two resolutions are no longer required, but they can be removed in another PR:
```json
"vscode-languageserver-protocol": "3.15.0-next.9",
"vscode-languageserver-types": "3.15.0-next.5",
```

**Comment by marcdumais-work** [comment]
@vince-fugnitto did you want to test this PR?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto did you want to test this PR?

I'm fine with it if you approve of it :) would you like to me to test it against a random image?

**Comment by marcdumais-work** [comment]
> I'm fine with it if you approve of it :) would you like to me to test it against a random image?

yes, good idea. One other than `theia-docker` that I already tested.

**Comment by perrinjerome** [comment]
@marcdumais-work @vince-fugnitto thank you

**Pull request merged**
