### PR TITLE
fix issue #260 - editor can no longer be saved

### LINKED ISSUE #260: [all images] Can't save from IDE
There is a recent breaking change caused by some change in one or more Theia NPM dependencies, that causes the save feature not to work.

The problem is still being investigated. See: https://github.com/eclipse-theia/theia/issues/6500

### PR DESCRIPTION
**Pull request by lmcbout**
Signed-off-by:Jacques Bouthillier <jacques.bouthillier@ericsson.com>

**Reference issue**
Fix #260 

**What it does**
It allows to save the text modification after editing.

**How to test**
Open any Theia-app
Open a file in the editor 
Make any modification  
Save it

**Review checklist**
- [x] as an author, I have thoroughly tested my changes and carefully followed the review guidelines

**Reminder for reviewers**
- [ ] as a reviewer, I agree to behave in accordance with the review guidelines

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@lmcbout as I mentioned, the issue should be resolved upstream (@marechal-p is looking into a fix), so there is no need to update all images.

**Comment by vince-fugnitto** [comment]
@lmcbout is it correct that the PR contains two commits?
 (I believe because it may be based off of #258)

**Comment by lmcbout** [comment]
@vince-fugnitto sorry, I did not mean to include your PR with mine, it should have been just one commit and I just did

**Comment by lmcbout** [comment]
@marechal-p  I agree with you, we will revert this PR when the main issue is solved. In the mean time, we can use the theia-app.

**Comment by marcdumais-work** [comment]
> I was tentatively looking at it in my yarn upgrade PR, but I have a hard time figuring things out.
> 
> This could be a good temporary fix to revert once everything is back in order.

Sounds like a plan - I would not mind waiting a bit for an upstream fix if our CI was catching the problem and preventing publishing of flawed images, but it's not.

**Pull request merged**
