### PR TITLE
Clean up linting errors from eclint

### LINKED ISSUE #410: repo: cleanup linting errors
**Description**

There are some minor [linting errors](https://travis-ci.com/github/theia-ide/theia-apps/jobs/384669032#L98-L104) reported during the build which we can fix:

```
1.20s$ eclint check "**/*" || echo "Warning! Formatting errors encountered..."
theia-electron/package.json
    - 17:01 invalid indent size: 10, expected: 12 (EditorConfig indent_size https://goo.gl/QtGB8R)
    - 19:01 invalid indent size: 10, expected: 12 (EditorConfig indent_size https://goo.gl/QtGB8R)
theia-full-docker/settings.json
   - 03:01 expected final newline
```

The [`theia-full-docker/settings.json`](https://github.com/theia-ide/theia-apps/blob/master/theia-full-docker/settings.json) file should be removed in favor of specifying the default values directly in the corresponding `package.json`:

https://github.com/theia-ide/theia-apps/blob/840ceaf00c41b387793f1849898db1a688083e6e/theia-full-docker/latest.package.json#L7-L10

https://github.com/theia-ide/theia-apps/blob/840ceaf00c41b387793f1849898db1a688083e6e/theia-full-docker/next.package.json#L7-L10

cc @DukeNgn

### PR DESCRIPTION
**Pull request by DukeNgn**
## Description:
+ Fixes #410 

## What changed:
+ Adjust indentations in `theia-electron/package.json`
+ Remove `theia-full-docker/settings.json`
+ Specifying value directly in `theia-full-docker/latest.package.json` and `next.package.json`

Signed-off-by: Duc Nguyen <duc.a.nguyen@ericsson.com>

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
I believe the `theia-full` docker image will fail at the following step:

https://github.com/theia-ide/theia-apps/blob/840ceaf00c41b387793f1849898db1a688083e6e/theia-full-docker/Dockerfile#L263

We no longer have the `settings.json` to be added.

**Comment by DukeNgn** [comment]
Thanks for the review. I'll remove that line, and also this because the config for PHP now in `package.json`

https://github.com/theia-ide/theia-apps/blob/060efa792ab87c6b3511682ad2e01bbad53dbf49/theia-php-docker/Dockerfile#L42

**Review by vince-fugnitto — APPROVED** [review]
The changes look good :+1: 
I'll wait for CI to finish before merging (and I'll verify the linting warnings).

**Comment by vince-fugnitto** [comment]
The changes look good, merging!

**Pull request merged**
