### PR TITLE
Ci add tests

### PR DESCRIPTION
**Pull request by marcdumais-work**
This commit adds a minimal test suite that validates that the images,
that we build and publish, include a minimally working Theia application.

Until now we relied on the success of an image's build during CI, to
publish it on dockerhub. That's not good, because Theia applications
can sometimes build but not behave correctly or even start.

The UI test suite and related configurations were borrowed from the
main theia repo and slightly adapted. ATM we use only the most basic
test suite, "main-page", that should be applicable to all Theia
applications we run CI on.

This will be enhanced in the future to to add image-specific test
files. For example, see wdio.theia-docker.conf.js, that adds an
extra test file to be run, for the theia-docker image. ATM this second
suite is bogus and just for demonstration purposes.

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@akosyakov FYI.

**Comment by marcdumais-work** [comment]
BTW, the failures for theia-full (latest and next) and yangster (next) seem unrelated to this PR and also occur in master.

**Comment by marcdumais-work** [comment]
Any objections to merging this PR? If not I'll merge later today.

**Comment by marechal-p** [comment]
There are failures with theia-full: https://travis-ci.org/theia-ide/theia-apps/jobs/476363206#L3461

Is this expected?

**Comment by marcdumais-work** [comment]
> There are failures with theia-full: https://travis-ci.org/theia-ide/theia-apps/jobs/476363206#L3461
> 
> Is this expected?

Yes, we have the same failures in the latest nightly build: https://travis-ci.org/theia-ide/theia-apps/builds/476134072?utm_source=github_status&utm_medium=notification

However, with this PR, we can now see where the failures occur, vs what we have on master.

**Pull request merged**
