### PR TITLE
split images: cpp, go and rust

### PR DESCRIPTION
**Pull request by marechal-p**
Finish splitting the last Dockerfiles to build Theia in its own image.

### CODE REVIEW

**Comment by DukeNgn** [comment]
I built and tested the PR on my machine. Everything works well 👍

**Comment by marcdumais-work** [comment]
I think we can wait a bit, and try to merge the following PR first, that touches the full image, since I think it will be easier than the other way around:
https://github.com/theia-ide/theia-apps/pull/425

**Comment by marechal-p** [comment]
I can drop the full image change commit, the other images are not affected right?

**Comment by marcdumais-work** [comment]
> I can drop the full image change commit, the other images are not affected right?

Do you mean to drop the full image from the current PR, merge the remaining changes immediately,  and bring back the full image changes in another PR, after #425 is merged?

**Comment by marechal-p** [comment]
@marcdumais yes.

**Comment by marcdumais-work** [comment]
@DukeNgn Since you tested this PR, I added you as a reviewer. If you're satisfied, you can add your official approval, now.

**Review by DukeNgn — APPROVED** [review]

**Pull request merged**
