### PR TITLE
[theia-docker] get rid of dev dependencies

### PR DESCRIPTION
**Pull request by akosyakov**
Locally it reduces the image from 412MB => 305MB.

### CODE REVIEW

**Comment by marcdumais-work** [comment]
I built a local image based on this PR. It seems that there is a dugite issue: 

```
root INFO 'USE_LOCAL_GIT' is set to true. Trying to use local Git for 'dugite' execution.
root INFO 'USE_LOCAL_GIT' is set to true. Trying to use local Git for 'dugite' execution.
root INFO 'USE_LOCAL_GIT' is set to true. Trying to use local Git for 'dugite' execution.
root ERROR Request repositories failed with error: Git could not be found at the expected path: '/home/theia/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging. Error: Git could not be found at the expected path: '/home/theia/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at /home/theia/node_modules/dugite/build/lib/git-process.js:86:39
    at exithandler (child_process.js:282:5)
    at ChildProcess.errorhandler (child_process.js:294:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
root ERROR Request repositories failed with error: Git could not be found at the expected path: '/home/theia/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging. Error: Git could not be found at the expected path: '/home/theia/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at /home/theia/node_modules/dugite/build/lib/git-process.js:86:39
    at exithandler (child_process.js:282:5)
    at ChildProcess.errorhandler (child_process.js:294:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
root ERROR Request repositories failed with error: Git could not be found at the expected path: '/home/theia/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging. Error: Git could not be found at the expected path: '/home/theia/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at /home/theia/node_modules/dugite/build/lib/git-process.js:86:39
    at exithandler (child_process.js:282:5)
    at ChildProcess.errorhandler (child_process.js:294:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Even though I have multiple git repos in my workspace, they do not seem detected: 
image

Playing with the image a bit, the situation seems to have resolved itself somehow, maybe after a client reload, and Theia's git client started to work. Weird. 

And if I go in a terminal, the dugite binary seems to be present, but I get an error when trying to run it, as if it were not: 
```
bash-4.3$ ls -al /home/theia/node_modules/dugite/git/bin/git
-rwxr-xr-x    1 root     root       2065872 Oct 30  2017 /home/theia/node_modules/dugite/git/bin/git
bash-4.3$ /home/theia/node_modules/dugite/git/bin/git
bash: /home/theia/node_modules/dugite/git/bin/git: No such file or directory
```

Maybe something that dugite depends-on was removed along with dev-dependencies? 


Another error about a missing bit, that I do not remember seeing before (json schema-related?): 
```
root ERROR Request getExtensionsInfos failed with error: Cannot find module 'ajv/package.json' Error: Cannot find module 'ajv/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at ExtensionPackageCollector.module.exports.modulePath [as resolveModule] (/home/theia/.application-module-loader.js:1:102)
    at ExtensionPackageCollector.collectPackage (/home/theia/node_modules/@theia/application-package/lib/extension-package-collector.js:53:32)
    at ExtensionPackageCollector.collectPackages (/home/theia/node_modules/@theia/application-package/lib/extension-package-collector.js:39:18)
    at ExtensionPackageCollector.collectPackagesWithParent (/home/theia/node_modules/@theia/application-package/lib/extension-package-collector.js:45:14)
    at ExtensionPackageCollector.collectPackage (/home/theia/node_modules/@theia/application-package/lib/extension-package-collector.js:62:18)
    at ExtensionPackageCollector.collectPackages (/home/theia/node_modules/@theia/application-package/lib/extension-package-collector.js:39:18)
    at ExtensionPackageCollector.collectPackagesWithParent (/home/theia/node_modules/@theia/application-package/lib/extension-package-collector.js:45:14)
    at ExtensionPackageCollector.collectPackage (/home/theia/node_modules/@theia/application-package/lib/extension-package-collector.js:62:18)
```

**Comment by marcdumais-work** [comment]
I am not sure why, but the dugite problem seems intermittent. On some container starts, I see this, after the dugite executable is not found : 
```
root INFO Using external Git executable. Git path: /usr/bin/git. Git exec-path: /usr/libexec/git-core. [Version: ]
root INFO Using external Git executable. Git path: /usr/bin/git. Git exec-path: /usr/libexec/git-core. [Version: 2.13.7]

```

When this happens, then the git client in Theia works as expected.

**Comment by akosyakov** [comment]
@marcdumais-work thanks for checking it

@kittaakos hi, do you have an idea why dugite behaves differently in the production mode?

**Comment by kittaakos** [comment]
I would not delete the entire `node_modules` foleder; that contains the embedded Git from dugite. We could get rid of the `ENV USE_LOCAL_GIT true` too.

**Comment by akosyakov** [comment]
@kittaakos 

> I would not delete the entire node_modules foleder

We don't do it, in the production mode, only dev dependencies should be installed. I cannot get my head around how it can break dugite.

**Pull request closed without merging**
