### PR TITLE
Improve grammar in README.md

### PR DESCRIPTION
**Pull request by jasonharrison**

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
Thank you for your contribution @jasonharrison.
Can you please `sign-off` your commit (reason for the failed CI check)

**Comment by marcdumais-work** [comment]
Hi @jasonharrison ,

Thanks for this. Could you please sign the commit and force-push to update the PR? e.g.
```
git commit --amend -s 
git push-f  origin/patch1  # assuming your fork's remote is named "origin"
```

**Comment by marcdumais-work** [comment]
@jasonharrison sorry for repeating @vince-fugnitto 's request - I should have refreshed the page before commenting.

**Comment by jasonharrison** [comment]
@marcdumais-work Not a problem, thanks for the instructions.  Please check now.

**Comment by marcdumais-work** [comment]
Thanks @jasonharrison ; merging.

**Pull request merged**
