### PR TITLE
electron: adjust the engines field

### PR DESCRIPTION
**Pull request by vince-fugnitto**
**Description**

The commit updates the `engines` field for both electron applications so it is aligned with upstream:
+ adjusts the engines field for the `theia-electron` app
+ adjusts the engines field for the `theia-cpp-electron` app

**How to Test:**
- build and package the `theia-electron` application
- the application should successfully start

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by marcdumais-work** [comment]
Good idea - this will help guide people who try to self-build these apps, while not being aware of the exact `node`and `yarn` version required to do so.

**Comment by vince-fugnitto** [comment]
Looks like I need to adjust the CI a bit (failing for the electron builds).

**Review by marcdumais-work — APPROVED** [review]
LGTM. Tested by building locally the `theia-electron` app. As expected it failed, the error refering to the `engine` field using node 10.x but succeed with node 12.16.1.

**Comment by marcdumais-work** [comment]
> Looks like I need to adjust the CI a bit (failing for the electron builds).

Up-to you if you want to do so in the same PR.

**Comment by vince-fugnitto** [comment]
@marcdumais-work fine to merge, or should I squash?

**Pull request merged**
