### PR TITLE
[full] add go and gopath dir permissions

### PR DESCRIPTION
**Pull request by satishbabariya**

### CODE REVIEW

**Comment by marcdumais-work** [comment]
Hi @satishbabariya ,

How have you validated the changes in this PR?

**Comment by satishbabariya** [comment]
@marcdumais-work, I tried the following scenarios
1. go get test -> `go get https://github.com/labstack/echox`
2. go module test -> 
```shell
export GO111MODULE=on
mkdir helloworld
cd helloworld
go mod init helloworld
...
```

**Comment by marcdumais-work** [comment]
> @marcdumais-work, I tried the following scenarios
> 
> 1. go get test -> `go get https://github.com/labstack/echox`
> 2. go module test ->
> 
> ```shell
> export GO111MODULE=on
> mkdir helloworld
> cd helloworld
> go mod init helloworld
> ...
> ```

Thanks @satishbabariya  - this will be useful to validate the changes

**Comment by marcdumais-work** [comment]
@satishbabariya I did not have much success with the suggested test (same result with `theia-go`), but I was able to successfully run this "test your installation" procedure: https://golang.org/doc/install#testing

**Pull request merged**
