### PR TITLE
[go] update vscode-go version

### PR DESCRIPTION
**Pull request by satishbabariya**

### CODE REVIEW

**Comment by marcdumais-work** [comment]
Hi @satishbabariya ,

Since you're updating this image, would you care to cover #154 as well, and make use of the VS Code extension for theia-go:latest as well?

**Comment by marcdumais-work** [comment]
I gave the PR a quick try: seems to still works well with an updated VS Code go extension. I was able to debug `go-gin-app`, as suggested in the initial PR where the go VS Code extension was introduced: https://github.com/theia-ide/theia-apps/pull/146

**Comment by satishbabariya** [comment]
> Hi @satishbabariya ,
> 
> Since you're updating this image, would you care to cover #154 as well, and make use of the VS Code extension for theia-go:latest as well?

@marcdumais-work , #207 is currently working on that issue.

**Comment by marcdumais-work** [comment]
Oh, I just noticed that the commit is not signed. Can you please sign it?

**Comment by satishbabariya** [comment]
sure, np

**Pull request merged**
