### PR TITLE
Adding maven and gradle for Java images

### PR DESCRIPTION
**Pull request by andreig**
Most of the Java projects require mvn or gradle so why not have them pre-packaged ?

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@andreig thanks for this PR!

One important detail however: we require a real email address be used in the commit. To fix this, I think you need to configure git on you machine, to use your real email address, and then amend the commit with option `-s` to update the signature.

**Comment by marcdumais-work** [comment]
BTW do not worry about the CI not passing. It's a know issue having to do with a security token, that affects non-committers in this repo. Before merging I'll create a PR with your commit and then the CI will be meaningful.

**Comment by andreig** [comment]
Yes, noticed that both checks failed initially, had to go back and add the signoff, hope it's ok now.

**Comment by marcdumais-work** [comment]
@andreig Thanks for giving this a try. Unfortunately it doesn't seem it worked: 
``` 
commit 71cfab3032185d885e814576f34ecef085c1173e (HEAD, andreig/master)
Author: git@openbsd-box.org <andrei@PHZQ001.cs1local>
Date:   Sat Mar 16 19:31:58 2019 +0000

    Adding maven and gradle for Java
    
    Signed-off-by: Andrei GUDIU <git@openbsd-box.org>
```
You might want to verify that you have run these commands or equivalent (using your name and email address):
```
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```
Then you need to amend the commit. It might help if you use the `--author` switch when amending the commit and use your own name and email address) Using `-s` should sign the commit with your newly configured identity, but you may need to remove the old one (`Signed-off-by: Andrei GUDIU <git@openbsd-box.org>`) manually when amending:
```
git commit -s  --amend --author="John Doe <john@doe.org> "
```
Let me know if you need help.

**Comment by marcdumais-work** [comment]
@andreig I created a bogus PR containing your commit. The CI should pass on this one: https://github.com/theia-ide/theia-apps/pull/149

**Comment by marcdumais-work** [comment]
Hi @andreig,

I see you have pushed an updated version of your commit(s). However the associated email is still a seemingly bogus one: `<git@openbsd-box.org>`. 

I'd like to get a fix in ASAP, to have Maven and Gradle installed in `theia-java` and `theia-full` - [others](https://github.com/theia-ide/theia-apps/issues/152)  are also waiting for this fix.

So if you could make the requested changes ASAP it would be great. Else I'll go ahead and make my own version of this PR.

**Comment by marcdumais-work** [comment]
Closing in favor of #158

**Comment by andreig** [comment]
@marcdumais-work this is actually my e-mail address, sorry if you consider it a bogus one :)

**Comment by marcdumais-work** [comment]
@andreig Sorry, it looked very much like a default address :(

**Pull request closed without merging**
