### PR TITLE
Add getting-started and editor-preview extensions to `next` builds

### PR DESCRIPTION
**Pull request by uniibu**
This commit adds `@theia/getting-started` and `@theia/editor-preview`  to all `next` builds.

Closes https://github.com/theia-ide/theia-apps/issues/104

Signed-off-by: Uni Sayo <unibtc@gmail.com>

### CODE REVIEW

**Comment by marcdumais-work** [comment]
Strange... I am unable to build locally. The same seems to pass on CI (fails much later, due to GH API rate limit)

```
theia-apps/theia-docker$ docker build --no-cache --build-arg version=next -t theia-docker:next .
Sending build context to Docker daemon  5.632kB
Step 1/18 : FROM node:8-alpine
 ---> df48b68da02a
Step 2/18 : RUN apk add --no-cache make gcc g++ python
 ---> Running in b3deee3b9ec4
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  g++ (missing):
    required by: world[g++]
  gcc (missing):
    required by: world[gcc]
  make (missing):
    required by: world[make]
  python (missing):
    required by: world[python]
The command '/bin/sh -c apk add --no-cache make gcc g++ python' returned a non-zero code: 4
```

**Comment by marcdumais-work** [comment]
(not directly related to this PR, BTW: I have the same on master)

**Comment by uniibu** [comment]
seems to be issue with your network? Seems to build fine on my end.

**Comment by marcdumais-work** [comment]
Hi @uniibu !

I did a quick run of tests, and found that, in a couple of images, Theia does not start correctly. However the issues may not be from your changes (most likely some extension used in these Theia applications need updates):

`next` images with issues:
 - theia-full: not starting (F-E: Error: Cannot apply @injectable decorator multiple times)
 - yangster-docker: not starting (F-E: Error: Cannot apply @injectable decorator multiple times)


Start correctly:
 - theia-docker: ok
 - theia-go: ok
 - theia-java: ok
 - theia-python: ok
 - theia-ruby: ok
 - theia-sadl: ok

I will give a quick try to the master version of the couple of images that have issues, to confirm they're not related to this PR.

**Comment by marcdumais-work** [comment]
I have confirmed that the master version of yangster-docker:next and theia-full:next have issues unrelated of this PR, that can be tackled separately.

**Pull request merged**
