### PR TITLE
GH-77: Added image to building electron applications for Windows on UNIX

### PR DESCRIPTION
**Pull request by kittaakos**
Closes: #77.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

**Comment by akosyakov** [comment]
@kittaakos do you want to add it to travis?

**Comment by kittaakos** [comment]
Good question; I would say no. There is not much to build, and it does not depend on Theia at all. In a nutshell: it is not subject to change. What do you think, @akosyakov?

**Comment by kittaakos** [comment]
> don't forget to propagate a GH token properly

Can you please explain why do we need it?

**Comment by akosyakov** [comment]
@kittaakos if it is not a part of travis then it does not matter. We need to avoid hitting the GH request rate limit by Travis while downloading vscode-rigrep.

**Comment by kittaakos** [comment]
> GH request rate limit by Travis while downloading vscode-rigrep

That explains. Thank you! I am merging this PR. The Docker image is available [here](https://hub.docker.com/r/theiaide/theia-electron-builder/).

**Pull request merged**
